version: '3.8'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/opt/app" 
    ports:  
      - "7860:7860"     
    tty: true
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860", "--reload"]

